# Generated by Django 4.2.6 on 2023-10-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slots_left',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
