# Generated by Django 4.2.6 on 2023-10-27 15:53

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_admin_categories_conversations_events_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
    ]
