# Generated by Django 4.2.6 on 2023-11-15 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_events_slots_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinions',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authored_opinions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_opinions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizators',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizator_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
