# Generated by Django 4.2.6 on 2023-11-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_events_latitude_events_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='totalSlots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
