# Generated by Django 4.2.6 on 2023-11-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_events_totalslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='slots_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
