# Generated by Django 4.2.6 on 2023-11-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_reservations_slots_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
