# Generated by Django 4.2.6 on 2023-11-20 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_reservations_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='events',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
