# Generated by Django 4.2.6 on 2023-11-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_events_end_time_events_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='end_time',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start_time',
            new_name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='events',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='start_date',
        ),
    ]
